//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lagu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public long id_genre_ { get; set; }
        public string nama_genre_ { get; set; }
    }
}
