//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lagu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lagu
    {
        public long C_id_lagu { get; set; }
        public Nullable<long> id_album { get; set; }
        public string nama_lagu { get; set; }
        public string foto_lagu { get; set; }
    }
}
